### ISSUE TITLE
it does not work at the outdoor 

### ISSUE THREAD

**Issue by xiaoxiaotao** [JeremyBYU/polylidar-realsense#4]
Hello,I use polylidar-realsense to detect ground at outdoor, but it not work.when I am at indoor , it work very well. My device is D435.Thank you !.

**Comment by JeremyBYU** [comment]
Hey Xiao,
First, thanks for looking at Polylidar3D and trying it out with some RealSense cameras. 

If its working "very well" inside and "not working" outside then its probably an issue with the depth image from the sunlight. I also have issues with my D435i outside in the sun, it only works for a very limited range. So my advice would be first to improve the depth image by adjusting parameters in RealSense, such as exposure time.  After this then adjust post processing filters, Polylidar3D mesh smoothing, and then Polylidar3D polygon extraction parameters

## RealSense Parameters

If you are using the `default.yaml` config file it has a link to load a JSON file which loads parameters to the camera in advanced mode: https://github.com/JeremyBYU/polylidar-realsense/blob/819a2f0f8daa2c18d1349e7b4bade075e06349a8/surfacedetector/config/default.yaml#L3

Right now it currently links to to `high_accuracy.json`. It is currently set to **manual** exposure with 8500 microseconds of exposure time.  This works well for me in my house and basement, but outside it would be quite bad. 
https://github.com/JeremyBYU/polylidar-realsense/blob/819a2f0f8daa2c18d1349e7b4bade075e06349a8/surfacedetector/config/json/high_accuracy.json#L19

I would change that to around 1500 or maybe even 1000 if you are outside on a bright day. Also note that you can use [RealSense viewer](https://www.intel.com/content/dam/support/us/en/documents/emerging-technologies/intel-realsense-technology/Intel-RealSense-Viewer-User-Guide.pdf) to change these parameters and then save the changes into a JSON file. That JSON could then be loaded by Polylidar-realsense.  Note that this doesnt apply to post-processing filters which are specified separately in the config file and are not apart of the cameras advanced parameters.

## Post Processing Filters

The realsense filters are very good. [Please read up on them if you haven't](https://github.com/IntelRealSense/librealsense/tree/master/examples/post-processing). I would make sure that you have adjusted them to give the best results for the scene you are interested in. Decimation filters do a really good job at smoothing and will lower the processing time for downstream filters.  The temporal filter is very valuable, but be careful to not overuse it! In high movement scenarios it will cause smearing, but if your scene can be roughly static then go ahead and crank it up. The spatial bilateral filter is also really great and will help to preserve edges. 

## Polylidar3D Mesh Smoothing 

I would leave [these parameters](https://github.com/JeremyBYU/polylidar-realsense/blob/819a2f0f8daa2c18d1349e7b4bade075e06349a8/surfacedetector/config/default.yaml#L50) alone for right now. But you can play with them around later if needed.

## Polylidar3D Parameters

Since the polygon extraction is  working inside then there probably are not any parameters here that you should change. However *maybe* you could lower `norm_thresh_min` here: https://github.com/JeremyBYU/polylidar-realsense/blob/819a2f0f8daa2c18d1349e7b4bade075e06349a8/surfacedetector/config/default.yaml#L62 . Don't really go any lower than 0.92, that allows a arcos(0.92) = 21.5 degree deviation from the estimated plane normal. Lowering that value allows more non-planar triangles into the segment and *could* help remove lots of small holes that may be generated form very noisy point clouds.  

You could also increase z_thresh as well: https://github.com/JeremyBYU/polylidar-realsense/blob/819a2f0f8daa2c18d1349e7b4bade075e06349a8/surfacedetector/config/default.yaml#L60

Maybe 0.20 or 0.30 at the highest.

**Comment by xiaoxiaotao** [comment]
Thank you very much !  I will have a try !

**Comment by dorinseggall** [comment]
Hi , 
i am trying to activate the code with the D435i , i am working on Ubuntu (with oracle VM Virtual) 
i finish all the clones process and try to run -
 python3 -m surfacedetector.capture.py -c urfacedetector/config/default.yaml 
and i received the next error : 

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/dorinse/dorin/polylidar-realsense/surfacedetector/capture.py", line 23, in <module>
    from surfacedetector.utility.helper import (plot_planes_and_obstacles, create_projection_matrix,
  File "/home/dorinse/dorin/polylidar-realsense/surfacedetector/utility/helper.py", line 83, in <module>
    def get_intrinsics(pipeline, stream=rs.stream.color):
AttributeError: module 'pyrealsense2' has no attribute 'stream'
can you help me , any idea ? 
thank you !

**Comment by sunwell1994** [comment]
@JeremyBYU As you mention, L515 cannot work in the sunlight as well. Do you have the number of the detecting range based on your experience? Thanks.

**Comment by JeremyBYU** [comment]
I think you are asking me to estimate the depth range of the L515 sensor.

In bright sun -> 0-0.5 meters
In medium sun -> 0- 0.9 meters
Dusk -> 0-1.5 meters
Just turned Night -> 0 to 3 meters
Pitch black -> 0 to 5

Inside  basement -> 0 to 6


These are just estimates from a foggy memory.
